name: Build and Release Dictionaries

on:
  schedule:
    - cron: '23 3 * * *' # Should run at 03:30 UTC (which corresponds to the update of JMdict data files) every day
  workflow_dispatch: # Allows manually triggering the workflow

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Run Build Dicts Script
        run: |
          chmod +x ./binaries/yomitan
          bash build_dicts.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dst/*
          tag_name: ${{ steps.date.outputs.date }}
          name: ${{ steps.date.outputs.date }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is an automated release of the dictionaries for ${{ steps.date.outputs.date }}.
            For information on how to use these dictionaries, please see the [README](https://github.com/MarvNC/jmdict-yomitan).
